name: scrountch
description: A simple home inventory application for the family.
publish_to: "none"
version: 3.6.0+49

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  file_picker: ^6.1.1
  csv: ^5.0.2
  path_provider: ^2.1.1
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DelaGothicOne
      fonts:
        - asset: assets/fonts/DelaGothicOne-Regular.ttf
    - family: Chivo
      fonts:
        - asset: assets/fonts/Chivo-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  image_path: "assets/images/app_icon.png"
